spring:
  application:
    name: rapid-ticket-ms

server:
  port: 80
  servlet:
    context-path: /rapid_ticket

app:
  rapid-ticket:
    database:
      host: ${DATABASE_HOST:localhost}
      port: ${DATABASE_PORT:5432}
      name: ${DATABASE_NAME:rapid_ticket}
      schema: ${DATABASE_SCHEMA:rapid_ticket}
      username: ${DATABASE_USERNAME:postgres}
      password: ${DATABASE_PASSWORD:admin}
      driver: ${DATABASE_DRIVER:oracle.jdbc.OracleDriver}
